// Auto-generated wrapper for process_audio
// Generated by esp32-jit wrapper system
// Args array size: 32 slots (128 bytes)
// Arguments: 4 (slots 0-3)
// Return value: slot 31


#include <stdint.h>
#include "audio_dsp.h"  // Include generated header

// Wrapper function to handle argument unpacking and return value
// Args are passed via a memory region (args_addr)
// [0..N-1]: Arguments
// [N]: Return value (if any)
typedef int esp_err_t;
#define ESP_OK 0


esp_err_t call_remote(void) {
    volatile int32_t *io = (volatile int32_t *)0x48210d40;

    // Argument 0: POINTER type float*
    float* input = (float*) io[0];

    // Argument 1: POINTER type float*
    float* output = (float*) io[1];

    // Argument 2: VALUE type int32_t
    int32_t len = *(int32_t*)& io[2];

    // Argument 3: VALUE type float
    float gain = *(float*)& io[3];

    // Call original function: process_audio
    uint32_t result = process_audio(input, output, len, gain);

    // Write result (uint32_t) to slot 31
    *(uint32_t*)&io[31] = result;

    return ESP_OK;
}
