// Auto-generated wrapper for test_dynamic
// Generated by esp32-jit wrapper system
// Args array size: 32 slots (128 bytes)
// Arguments: 0 (slots 0-0)
// Return value: slot 31


#include <stdint.h>
#include "dynamic_print.h"  // Include generated header

// Wrapper function to handle argument unpacking and return value
// Args are passed via a memory region (args_addr)
// [0..N-1]: Arguments
// [N]: Return value (if any)
typedef int esp_err_t;
#define ESP_OK 0


esp_err_t call_remote(void) {
    volatile int32_t *io = (volatile int32_t *)0x48214510;


    // Call original function: test_dynamic
    int result = test_dynamic();

    // Write result (int) to slot 31
    *(int*)&io[31] = result;

    return ESP_OK;
}
